# DCEs Automation/Integration 


| pack/func | Features | MXL design | rand exp | create survey | run survey |
|:--------|:-----------:|:-----------:|:-----------:|:-----------:|:-----------:|
| formr   | 网站/包 |                |          | rand items |
| formr4conjoint |         |               |          |
| conjointTools  |         |               |          |
| idefix  |          | Bayesian adaptive |          | 
| DCEtool | local machine | 包装idefix |  |  
| ExpertChoice |  |  |

Table: Design, survey and analysis

通过搜索python conjoint, 终于找到合适工具

1. [conjointSDT.exe](https://github.com/astrezhnev/conjointsdt) Conjoint Survey Design Tool一个封装好的软件应用, 能实现attribute order randomization, 但是不知道里面DCE怎么设计的?没有D-optimal 
	- conjointSDT.py是文本文件, 试试找里面att order random的代码
	- 功能代码还是要到四件套里面找R coding
1. 上面conjointSDT推荐的估计模型R包[cjoint](https://cran.r-project.org/web/packages/cjoint/index.html)
1. [Pythonbiogeme](https://transp-or.epfl.ch/pythonbiogeme/), an open source freeware designed for discrete choice estimation.

1. Kaufman has a [Plos ONE](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0232424) and [GitHub](https://github.com/aaronrkaufman/shinySurveys) with focus on DCE ShinySurveys
    - 文章里实现4个功能,如DCE问题随机化, 但在RStudio Cloud和RStudio都页面闪退, 因此以后网调稳定还是很重要
1. Jonathan Trattner has a formal R package [shinysurveys](https://shinysurveys.jdtrat.com/) aims create and deploy surveys in 'Shiny'. *第1和第2重名但无overlap*
1. John Paul Helveston used formr.org to create a specific [formr4conjoint](https://github.com/ctang83/formr4conjoint)  
    - formr利用OpenCPU和Google form, 可能更稳定
  	- 如果formr无法用, 就直接用Google Forms, which可以实现DCE的[问题随机化](https://support.google.com/a/users/answer/9308764?hl=en)

## Design SP

Basic information for this part:

1. Orthogonal design 
1. fractional factorial design
1. efficient design (best choice)
		1. D-optimal design (optimal = maximally statistically efficient), 效率系数并非越大越好, 越大会降低[choice consistency](https://doi.org/10.1086/586913)

`install.packages("idefix")`
this R package combines designing DCE and dashboard implementing survey to collect data, all tasks can be conducted by using R and Github

```r
install.packages("remotes")
remotes::install_github("jhelvy/conjointTools")
```
[conjointTools](https://github.com/jhelvy/conjointTools), designing surveys and conducting power analyses for DCE,可以D-optimal设计,安装如下
*conjointTools*的作者John有一门特别好的课[Marketing Analytics for Design Decisions](https://madd.seas.gwu.edu/2021-Fall/c7-utility.html)

- help dcreate  //DCE设计Efficient designs

## Survey

`install.packages("DCEtool")`   
A complete package for creating, surveying, and analysing DCEs on local machine, including:
1. *idefix* to create the exp design, and present interactive survey by Traets et al. (2020)
1. *survival* and *mlogit* to analyse results
1. new code for visual interaction dashboard

### TO-DO-LIST
1. randomization in displaying of attributes for each choice task
	- 文献里叫attributes ordering effects, Randomize the attribute order, 有几种情况:
	- (1)一个respondent加入,其n个choice set的attribute order随机化,实现难度大
	- (2)500个respondents,手动分2-5种attribute order版本的questionnaires, 再shuffle respondents随机进各版本
	- we can't do a complete randomization of attribute order, because some attributes are ususally grouped. 
1. formr [randomise items/blocks](https://github.com/rubenarslan/formr.org/wiki/How-to-randomize-items-and-blocks)
1. randomization of respondents across blocks, e.g. A-B-testing or experiments, or[adapt question texts to sex/age](https://github.com/rubenarslan/formr.org/wiki/How-to-adapt-question-texts-to-e.g.-the-participant's-sex-and-relationship-status)


## Initiatives
For typical DCEs, we usually undertake the experimental design using Ngene, then hire a company such as SurveyEgine to program the survey and collect data, and finally analyse data using Stata or R. This process has several disadvantages as below:

1. disintegrated workflow, and thus needs coordinators at different stages;
1. generating lots of documents and files in different forms, e.g. words, excel, html files, coding files;
1. difficult to debug when unexpected results arise;
1. substantial costs by using external services from, e.g., Ngene and SurveyEgine.

To resolve these issues, I propose an automated and integrated solution using free and open source as listed below:

1. Step I, the project is built and synchronised between GitHub website and R local machine, and all files are using Rmarkdown language for both writing and coding;
1. Step II, we design a simple DCE (for pilot purposes) with orthogonal main-effect arrays using "support.CEs" package in R, or we design a DCEs with Bayesian adaptive designs for the mixed logit model using *idefix* package in R (*DCEtool*包装了idefix);
1. Step III, after generating choice sets and questionnaire, we create interactive dashboard html files using "idefix" and shiny application in R;
1. Step IV, all files are sychronised and deployed by the GitHub, then we obtained the website link for survey and data collection (using our own database or pay a data panel provider to do it);
1. Step V, we analyse choice data and do estimation by using either packages in R directly, or Stata coding (both inline and from a .do file) from R.
