--- 
title: "My Notebook"
author: "CTang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ctang83/NB_tang
description: "Recording my learning stuff."
---

# Intro & Records {#intro}

This notebook covers my daily improvements in both knowledges and skills.

## 2022年  

### Feb

- Debug: RStudio couldn't work well if R libraries are synchronized, I'm considering transfer the platform to RStudio Cloud, like Deepnote-Python.

### Jan

- 以下情况不需要伦理审查 Do I need to apply for ethics approval? In cases where data are collected for the purpose other than research, you might not need to submit an ethics application. This might be the case if your project falls into one of the following categories of data collection or use:

1. **Archival data, if it is from a public domain** Please note, you will have to apply for ethics approval if the information you intend to use is identified personal information (states or implies identity), not in a public domain or if you will collect data in addition to the archival research.

2. **Administrative data collection** Collection of data from staff or other stakeholders for the purposes of informing or improving a process within your organisation is not considered research. Still, if you later decide to use this data for research purposes, you will need to apply for ethics approval. In addition, the use of identified data always requires ethics approval.

3. **Teaching and learning** If you collect human data solely for teaching or learning purposes and do not expect to publish or present any data, no ethics application is necessary. However, if you think the project may be published, it is recommended that you apply for ethics approval before running the project, as this is easier than getting approval subsequently.

4. **Quality assurance or clinical audit** Usually data collected for quality assurance purposes or an audit, does not require ethical review, if it is for your organisation's own information. However, if information is to be taken outside the organisation and used for a published paper, research project etc, this is considered research and requires ethical review.

5. **Negligible risk research involving collections of non-identifiable data** Your research involves negligible risk if you use existing non-identifiable data or records or if it does not involve any foreseeable risk of harm or discomfort, which means there must not be the possibility of anything more than inconvenience. Although in this case you are not required to apply for ethics approval, you will probably need to complete a form to confirm that the project is of negligible risk, and provide a letter (or similar evidence of approval) from the person in charge of the data.


## 2010-2012年  

### 8月25日

关于申请2012年“国家优秀自费留学生奖学金”的通知   2012-08-09 我可以申
Win episcope 等级评分也是定性资料！  误差条图error bar chart 84-91-205
Approximately=a number of=some    
各国都是以民营医疗为主体的现实...国进民退会不会体现在医改投入的效果中？私医院会不会退潮？降温？也就是政府医改投入对私部门的挤出？
me：  0404142385   bao： 0404151559    PassPort:  G55112399
1/28 FORSYTH STREET, Kingsford, NSW, 2032        2816 chengxiang
Essays on Physicians' Choice             
Changes in drug utilization following the outpatient prescription drug cost-sharing program--evidence from China's 

Win episcope 等级评分也是定性资料！  误差条图error bar chart 84-91-205
Approximately=a number of=some  bao： 0404151559    PassPort:  G55112399
各国都是以民营医疗为主体的现实...国进民退会不会体现在医改投入的效果中？私医院会不会退潮？降温？也就是政府医改投入对私部门的挤出？
1/28 FORSYTH STREET, Kingsford, NSW, 2032        13540617813
LCA有两个models：choice model, class membership model
R 有个BayesLCA包，刚出，非常适合latent class model
White, A. and T. B. Murphy, et al. (2014). "BayesLCA: An R Package for Bayesian Latent Class Analysis." Journal of Statistical Software 61 (13).

air quality improvement, latent class, preference heterogeneity:
prefer status quo, prefer change??
One observable determinant of this preference heterogeneity is the 
exposure of individuals to health risks relating to air quality

利他 对 气候变化、器官移植影响？？？925452379636
how to divide classes in public and private hospital study: public-oriented, non-public-oriented patients

DCE topics: organ transplant, blood transfusion, drunk driving, 
weather and agriculture outcome



health & policy focus on "health shock + regression discontinuity"
labor focus on "tournament theory"
3 the health and health expenditure impacts of prostitution regulation in aus
http://en.wikipedia.org/wiki/Prostitution_in_Australia
http://en.wikipedia.org/wiki/Prostitution_and_the_law#Victimhood_issues


拟凹函数是定义在凸集上的满足以下性质的函数：任意两点的凸组合的函数值不小于这两个点的函数值中较小的一个；等价定义是这个函数的任一优集是凸集；如果二阶可微，则加边海赛矩阵的是半负定的

凹是基数性质，拟凹是序数性质，序数性质指在正单调变化下保持不变的性质  单调函数一定是拟凹的

拟凹性对最大化最小化问题是否有全局解，是否有唯一解的判断有用

假设一个消费者的 Bernoulli 效用函数是 u(x)=X^1/2他面对彩票 g=(1/2。16, 1/2。4)计算消费者的确定性等价 ...

Certainty Equivalent: c^(1/2)=1/2*16^(1/2)+1/2*4^(1/2)得到c=9;

Probablility Premium:(1/2+x)(10+6)^(1/2)+(1/2-x)(10-6)^(1/2)=(10)^(1/2)得到x=[10^(1/2)-3]/2,这个就是probability premium,这里消费者的初始财富是10.

闭合形式解：一个能直接计算级数和或递归结果的等式。
通常来说: CLOSED FORM SOLUTION 是解析解, (相对于数值解而言)

---

见到很多文献中的牛人 G Bloom, T Evens, W Hsiao,  牛美女梁.
认识了不少研究者,美国的,国内的.
国际学术会议是需要做很多准备:一参与者的背景调查,因为他们会找你谈话,要认识牛人,如福籍美国的洪燕教授,还有哈佛的研究员.二是提高自己的英语听力和口语,两者缺一不可,这决定你能与他们交流的基本前提.三是学术水平,当然这还好,毕竟自己兴趣最重要,不指望结识所有研究者,而重在认识自己兴趣领域的.
学术会议是自由平等的场所,要勇于展示自己,这次自信心不够,不敢一开始站在自己海报前向有兴趣的研究者介绍自己和研究,错过认识更多人的机会.第一天上午本就有很多人看我海报,可惜我没信心上去介绍和攀谈,而学术会议最重要在于认识和展现自己,直到下午一小时必须站那,可惜没认识几个时间就过拉.另一个就是找自己感兴趣的研究,并主动攀谈研究者聆听其研究和看法最后要名片建立联系.这次回去可主动找西北大学那个表示兴趣和未见到他的遗憾.
另海报比口头展示更提高自己和人沟通的机会和技巧,我第二天发现不少口头展示听者聊聊了,所以学术会议每一分钟都价值千斤,要前期认真准备,中间认真听演讲努力展示自己研究课题和兴趣,多主动找兴趣类似研究者聆听他们的研究再建立联系,会后主动帮助她们沟通和联系她们. (自己名片必须的)

---

文献综述一篇，关于影响药师工作绩效的多因素。
http://www.sciencedirect.com/science/article/pii/S016885101100114X
 
Human Capital的定义和表现形式值得借鉴：
http://www.nber.org/papers/w17474.pdf
 
如何组建包含地理信息和distance的数据库，并计算对健康补助和健康产出的影响
http://www.nber.org/papers/w17471.pdf

we own more knowledge, but use less

可惜共產革命在１９８９年就已經證明失敗了，不然全民公務員化還真是個救經濟、救失業的好點子

菲尔德斯坦说：医院的政治行为简直是描述经济学上自利人模型的完美例子。

Defenders of the new law invariably ignore the supply side of the market. They assume that if you insure the uninsured or give people more generous coverage that they will all get more health care without ever asking: who is going to provide that extra care?

Purports to control total spending on physician services, but it controls only prices, even though spending is the product of the price and the number and intensity of services.
We've seen that diagnostic imaging costs more in the U.S than elsewhere, but what about physician fees? This is arguably the most subjective part of the health care system. For example, do some countries value their physicians more than others? What about the emphasis on primary care versus the various specialties? 

---

关键词：
health care price physician specialization
price regulation medical profession specialization
regulation primary care physician specialization
health economics labor division
topics in medical economics specialization
division of labor  physician

division of labor  physician specialization
physician fees医生费

Physicians can sell prescriptions directly to patients.  Unsurprisingly, Japan has the highest consumption rate of pharmaceuticals per capita in the world.

背后的信念是因为确认医生在诊断和处方上有专业的技能,但非配药.相反,药师则在配药上有专业的训练。

所以，配药包括：“病人并可以选择在任何药房配药,而所配之份量亦可以依据病人的需要或经济上之不同而有所改变.同时处方上的不清,或病人不明百之处,药师可以直接与医生联络,立即改正处方或因应医生指示建议病人再访医生.再者药师亦能于释出药物时提供病人直接的服药指导.病人可在任何时候再访药房询问有关药物问题,而不需任何费用。配药学不只是数药丸,其实,药物的管理,病人的辅导更为重要”--即监督医生、校正处方、调整药品、指导病患。

咨询药物是否有FDA审核，副作用，还有什么别的现存药物治疗我的疾病，新药的最新资讯，有替代的非专利药物吗(Generic Drugs)，非专利药物是否和我的有商标名称的药物(brand-name drugs)本质类似，其效果又如何，有非处方药(OTC)吗，其与处方药有差异吗，有没有饮食补充方法，我从哪里找这些饮食信息？

Approved Drugs
    * How is medicine approved by FDA?
    * How can I find out if my medicine is approved by FDA?

Side Effects
    * How can I find out about side effects or safety concerns for my drug?
    * Do drugs have risks?
    * How do I report a suspected drug side effect

Treatments for Medical Problems
    * What approved drugs are available to treat my disease?
    * Since FDA cannot provide information about drugs in development, where can I go to learn more about them?

Generic Drugs
    * What are generic drugs?
    * Is there a generic equivalent for my brand-name drug?
    * Are generic drugs as effective as brand-name drugs?

Prescription Drugs and Over-the-Counter (OTC) Drugs
    * What is the difference between prescription drugs and OTC drugs?

Dietary Supplements
    * What is a dietary supplement?
    * Where can I find information about dietary supplements?

第一步亦是最易接受的就是争取病人的"取方权"--这是属于四种策略哪种？

--重要的不是在哪买药，而是经济环境条件是否更适合医生和药师选择自己怎样专业化，也就是医生和药师的选择，只要他们选择好了，其他都不是问题！

医生可以直接卖药给患者，而不是医生只提供诊断服务和治疗建议，由药师配药。这就是SPD问题，本质上是分工问题，药师没有参与到患者的治疗过程中来。常常导致的问题就是人均药品消费超高，即使发达如日本也不能例外。

Modern prescriptions evolved with the separation of the role of the pharmacists from that of the physician。

我的兴趣：
一个是分工理论在GP-physician和doctor-pharmacist的演化中的作用
二是中国卫生系统--这个无论是价格机制还是分工机制都messy的东西

从历史来看，药剂制作和（类）药剂师的出现，无论中国和西方都有几百上千年的历史，见Du liping的"Professional Code or Legal Sanctions: Pharmacy in China"和"Kremers and Urdang's History of pharmacy"
 By Edward Kremers, Glenn Sonnedecker这两本书。

中国会不会存在这样一个问题：
因为价格机制管制→导致GP-physician和doctor-pharmacist的分工无法演进？
也就是说fixed price system→分工停止（虽然也有人为的复制西方分工体系，但多失败）→效率无法提高？

换句话说，价值制度决定分工水平和演进

Folland的卫生经济学书version6的第338页有讲physician的专业化一小节，注意是physician，不是全部medical professions。

差异化和专业化有什么区别？有什么关联？

亚当·斯密为代表的古典经济学关于劳动分工是经济发展和增长的原动力这一伟大洞见，提供了微观机制和数学框架
劳动分工理论对于管理理论的发展起到了十分重要的作用，后来的专业分工、管理职能分工、社会分工等理论，都与斯密的这一学说有着“血缘关系”。
阿罗称赞杨的研究使亚当。斯密的劳动分工论与科斯的交易费用理论浑为一体

---

全民健保名字里虽然有保险，其实不是保险，而且比保险更糟。
可以精算交通事故的机率，可以精算汽车险保费，但是病有万万种，台湾的健保早就没有精算疾病机率的这个程序了，因为根本做不到。没办法精算大小疾病的机率，健保管理就不是保险管理，而是预算管理。
健保比保险更糟，是因为保险里「第三方付费」的机制，在精算机率和政府监管的前提下，原本问题不明显。但是一旦健保变成预算管理，那使用者不管帐的第三方付费机制，就成了非常严重的「代理人问题」。
民众缴了保费，就不用管健保局怎么和医院打交道，也没有任何节省医疗支出的诱因，所以不看白不看。而且恶性循环，医疗费用因为民众不看白不看而愈来愈高，健保局只好调保费，而保费调愈高，民众愈觉得不看白不看。不管是一代健保的个人所得，或是二代健保的以家户所得计算基础，原理都是在调保费，没有任何解决「代理人问题」的机制。
芝加哥大学教授、曾获诺贝尔经济学奖的贝克（Gary S. Becker），评论欧巴马的健保改革时说，问题就是出在保险，健保改革还扩大保险的范围？很不幸，我们的健保已经是全民强制纳保，也就是说，我们早就走上医疗支出无法控制的不归路了。一项鲜为人知的数据是，台湾人缴的健保保费已经比综合所得税还多了，而且以后只会更多，不会更少。
英國公醫制度在不少人眼裡也許沒什麼不好，但是英國的醫療品質在歐盟裡最差，醫生收入、地位最低，醫療支出還名列前茅也是不爭的事實。

---

There are 6 features which contribute to the benefits on a popoulation's health,  associated with primary care.  (Starfield et al., 2005)  These benefits are improved access to services, improved quality of care, more emphasis on prevention, early management of health problems, combined effect of primary care delivery characteristics and the role of primary care in reducing unnecessary and potentially harmful specialist care.  (Starfield et al., 2005)

General practice was first introduced into parts of urban China in 1999.  (Liu, 2005)  CHC was introduced in 1998.  (Pan et al., 2006) 

a major determinant of a patient's satisfaction with care provided is their initial expectations, which can be shaped by a number of variables, including "socio-demographic and socioeconomic factors, past experience, needs, and word-of-mouth influence."  (Tam, 2007)Recently research seeking to understand patient's perspectives has moved from asking about patient satisfaction, which can be difficult to interpret to enquiring about patient experiences with healthcare.  (Davies and Cleary, 2005) 

The John Hopkins PCAT's four main domains assess the structure and process of primary care service provision

The John Hopkins Primary Care Assessment Tool was selected for use to assess patients' experience of quality.  Measuring patient experience of quality rather than patient satisfaction was a key feature when choosing the research instrument, given increasing dissatisfaction with measuring patient satisfaction, due to difficulty in interpreting patient satisfaction results.  (Berendsen et al., 2009; Davies and Cleary, 2005)

---

As part of the calculation of sub domain scores a score of 9 - not sure, was converted to a score of 2.5 for all sub-domains, except comprehensiveness, where a score of 9-not sure was converted to 0.

Instead, during the interviews the research assistant conducted the interview and the translator translated the main points of the interview as the interview was ongoing. This allowed the opportunity to ask some questions as the interview progressed.

---

Rozi，你要注意：extent of affiliation和 ongoing care是同属于一个主构面下面的分构面。

在6个缺失变量里，即无法确认PCP的的患者里，z贡献了5个，而我只造成一个

讲一下本科生的gp实习问题，
安泰中心实习两周变为一周
而r在英国两年时间里每周要去gp诊所实习一个下午，在第四五年级每年都要去实习4周，如果把实习作为一种暴露的话，那么是否更长的实习时间能够影响医学生下基层工作的意愿呢？以前看过一篇类似的JAMA的文章，就讲美国的医学生受哪些影响更愿意从事内科和家庭医生

以下记录几个我和rozi发现的，还可以继续研究的课题：

1、看病时的隐私，针对大医院诊室里病人的拥挤和不排队现象。提问：是否我们的病人就真的不在乎隐私呢？

2、为什么医学院校把两周的社区卫生服务实习时间改为一周，因为对比UK的培养体制，他们的医学生大量时间在GP实习

3、CHC的病人上午下午极不相同，上午挤了很多人，下午有3-4个医生却没有病人。虽然他们说下午医生都去家庭访视了，但是R和我奇怪，他们在做完health records以后，还用每天下午都去居民家中，如果去的话都是提供什么服务呢？ --120元的限价

---

FDA–which determines effectiveness of a drug regardless of cost

NICE–which determines not only whether a drug is effective, but whether these health improvements are worthwhile considering the drug’s cost.

“当医生不知道一个检查、一片药丸要多少钱的时候，医改就成功了。至于民众是否看得起病，那就是保障体系建设的问题了。”廖新波说。--------这个命题假设是否合理？？待检验

社会医学课程---预防、临床（其实质是治疗医学）、康复及临终关怀，三块分了病人

不是所有人都相信中国宏伟的医改方案会取得成功。上海一家大医院的资深外科医生宋科瑛认为医改在短期内不会有什么效果。宋医生持有中国和美国的两个医学博士后学位。他指出医改方案缺少面向医生的激励政策，因为国内医生的待遇比西方同行要低很多。因此，他认为要减少医院的药品销售提成很可能不会奏效。至于总值8500亿元的投资，宋医生认为中国市场太庞大、医院数量太多，单个社区卫生服务中心收到的投资将非常有限。他认为医改应当解决医生的低待遇处境，而医改方案中并未提到这个问题。

医改还在细节处，公共政策还在细节处。医疗成本与财务权多大程度控制在个人手上有正相关，当然它还受其他如支付方式、保险影响。

想法：经济水平和卫生服务人员的配置模型，本来卫生人资配置主要考虑疾病需求和收入，这里从经济水平寻找一个平均标准，并测算福建地域内的配置是否合理。

全文-----专门的数据库生产商---EBSCO、OVID、ProQuest
全文------出版社或专业学会------ElsevierScience、Springer、John Wiley
全文和文摘----联机检索系统----Dialog
文摘为主------OCLC FirstSearch、Scopus（包括社会科学方面的信息资源）
EBSCO全文数据库（含文摘或全文）

paper多数是指高校的学术论文与研究 这个词多用于美国英语

essay的意义跟paper差不多，不过一般是更短更简单、有特定主题的那种，它的学术层次比paper要低一些，许多时候是指就一个具有争议性论题所进行的讨论。

### 2011年5月24日

–  Visa/Passport information	  ★ --whenever扫描发过去都行
–  Proof of English Ability	  
–  Notarised/Certified Transcript	  
–  Details of previous research	  
–  Sponsorship Letter --（You must download the Sponsor Contract Form, which must be completed and submitted to the relevant Admissions Office.）   ★  --没影响
–  Research Plan	  
–  Proof of contact with supvsr	  ★
–  Curriculum Vitae

1.没有办护照，没有visa信息，能不能推迟给而不影响奖学金申请~   推迟的话，最后的日期是多少，可以说明你现在不在户口所在地，护照办理不方便
2. 之前邮件中提到的 Sponsorship Letter 问题，是你犯的一个错误，在提交申请资料的时候，遇到Will you be sponsored by an Official UNSW
Sponsor ?时，你应该选择NO，但是你选了yes，事实上商学院并没有和你谈及至奖学金，只是小蜜提醒你可以申请这个奖学金。

昨天决定，接受ucf offer（中佛）。我有以下缺点：
1）  我的本科学校及美国的学校都一般。
2）  没有金融的推荐信，虽然我的推荐人肯定会强力推荐，但作用应该不大。
3）  没有金融方面的论文。
4）  年龄已经大到影响申请。
5）  背景太复杂，多半人并不喜欢。
所以我申请的定位并不高，除了Rice 算好一点（但第一批得到拒信， 其他的都一般。offer得到的很早，funding 很好，20000GTA+5000summer fellowship, 如果 暑期教课，每门3000， 不过也就教一门课吧，因为他们学校要求前两个暑期各完成一篇论文。 钱对我很重要，关系到全家人的生活，所以接到这个offer后，基本上就不再考虑offer低于20000的学校了。

2.对于研究方向，如果不是特别清楚（其实我觉得在入学前，根本不必要把自己的定位搞得太死板），不必太执著于某一方向，选校时要综合考虑，但是在自我陈述中一定要指出来，根据不同的学校，应有不同的研究方向。
3：选校时可以把简历发给PHD coordinator, 让他们看一下，顺便问一下学校招生情况，多半时候会有答复，从回信中可以看出他是否对你感兴趣。positive的回复不代表offer, 但恢复若是negtive， 就一定不要申请， 无论你多想。
4：尽早完成申请，越早越好，并不是所有学校只有到截止日期后才审材料。
5：陶瓷可以，但最好在审材料以前。
6：申请的时候越仔细越好。
7：没有哪个学校可以保底，你申请的最差的学校只不过是你的底线而已。

letters of recommendation should address your potential as a scholar based on their experience  with you as a student, research assistant, or teaching assistant.

---

美国大学的研究生奖学金，对于国际学生而言，主要分为两类：非服务性奖学金（Non-Service Scholarship）、服务性奖学金（Service Assistantship）。非服务性奖学金包括Fellowship（学院助学金）、Scholarship（奖学金）、Tuition & Fee Waiver（全免学杂费）以及Awards（奖励）。
1．Fellowship是金额最高、但竞争最激烈的非服务性奖学金。一般情况下，获得Fellowship，便是获得了全奖，即除了免学费杂费、住宿费、保险费、书本费以外，还给获奖学生一定金额作为其个人消费费用。
2．Scholarship形式多样，可以是作为某种奖学金形式颁发给成绩优异的学生，也可以是免除学费或杂费。Scholarship的具体金额，也会随着学院规定的学杂费金额高低而不同。Scholarship不像Fellowship那样只有一种形式，在同一所大学可能设置几种甚至十几种不同形式的Scholarship，一个学生也可以有资格同时申请两种以上的Scholarship。
3．Tuition & Fee Waiver：在一些美国学院中，设有全免学费的奖学金，有的学院把它作为Scholarships的一种，有的学院把它单独列出。全免学费是在非服务性奖学金中最易申请的一种，然而虽然免去了学费,但由于学费只是总花费的一部分，所以如果要获得足够的资金，还需同时申请其他形式的奖学金。

服务性奖学金包含Teaching Assistantship（简称TA，助教），Research Assistantship（简称RA，助研）和On-Campus Job三种。获得TA/RA的资助者，每周需担任12-20小时的辅助教学或研究工作。这种经济资助只提供给硕士或者博士申请者。对于申请美国研究生以上级别的中国学生来说，获得奖学金的机率会比本科生或本科转学生大得多，多数都是以拿到这两种服务性薪金的一种来获得全奖的。绝大多数的美国高校研究生院，都设置这两种资助，然而并非所有学院的此类资助都能覆盖一年中的全部费用，但多数都在全部金额的2／3以上。不过很多学校提供这种奖学金的同时，还会给学生免学杂费，也就相当于申请到“全奖”。不过，TA/RA所得是要纳税的。校内工作 (On-Campus Job)也是服务性薪金的一种，学生通过学校提供的校内工作来获得一定收入。美国移民局规定，国际学生可以在校内合法工作，每小时最低为5.15美金，每周最多可以工作20小时，假期可以工作40小时。校园工作包括在大学食堂、书店、图书馆或健康俱乐部等地方打工，或者在大学的行政办公室帮忙。

### 2010年10月

十所学校选定，UGA看情况说。

我们强烈推荐所有申请者查看HPM课程在申请前。

PhD申请
面試這種事情
做久了會彈性疲乏
所以大家要找工作
最好在工作一開放就趕快去丟
你越晚丟
你就處於越不利的狀態
這是基本初步的建議

1強大的邏輯能力
2精確的知識引用能力
3並清楚自己的賣點

50之前的都要牛推！我恐怕很难啊

你直接跟张老师联系下 问问清楚
或者直接打办公室电话 问问管学生教学的
这个事情建议你回来直接找哈王亨洪或李洪军
你要是去教务处, 他们是可以给你开证明，

Philosophy of economics, economic methodology, history of economics, relation of economics to social values, social economics, ethics and economics, health economics, international economics.
Philosophy and Methodology of Economics, History of Economics, International Economics, Ethics and Economics, Health Economics.

邮寄材料到北美-EMS-15天，国际快递5天内, 可寄龙翕，他转寄，省钱，他一封6刀
DHL：中外运-敦豪福建分公司 中国福建省 福州市仓山区盖山投资区高旺路9号5号楼1-2层 + 86 (591) 87321111 350007 否   请您拨打800-810-8000预约取件 

GRE 建议NO.的填空做2遍,
因为填空句子比国内题句子稍难,但逻辑很清晰,对做题思路的训练很有帮助
-ive结尾，表示人喜欢做这件事
GRE考得多的单词可以看出美国人对其的偏爱，哈哈
类比关系要有必然性在里面：比如“灵巧的人”是“灵巧的”

### 8月25日

福州仓山区中医院数据输入了两遍
保护坏参与者会伤害所有参与者，而且帮不到任何人
Win episcope
重要的經濟觀點，通常是正確但不明顯(universally true, but not obvious)
等级评分也是定性资料！！切记
10.100.246.38 / 254
10.46.2.16

2号线6站到中山公园转3号线
My confirmation number is 8850000000499691. 
REGISTRATION NUMBER:  6610367
登陆时用confirmation那个 连日期都不用输

顶边1.85+1.45
读-听-说-写

### 6月27日

1、为什么我们要相信你有在这个领域做研究的潜力？
2、你觉得你正在做什么？为什么？
3、好的PS包括你做过的项目和这个领域相关研究的引用！
the most important character trait in research is not intelligence, but self-disciplin. So, if you want prove that you have potential, prove that you have the fortitude to take on the system
217-4184643 谢亮手机

Food Science and Engineering
Food Sci & Engineering
Business Administration
Social Medicine & Health Administration

09/01/2002
09/01/2004
06/30/2006
baccalaureate degree
Fujian Medical University
09/01/2008
06/30/2011

Lieping Chen
clpqsc@126.com
Fujian Medical University
0086-13763834045

Weiguang Zhang
zwguang@swu.edu.cn
Southwest University  College of Food Science
13983485159

Rosalind McCollum
Concern Worldwide
rosalind.mccollum@concern.net
Ireland

Chongqing
Southwest University
Attended From 09/01/2002 To 06/30/2006
Degree Bachelor of Engineering Received 06/30/2006

Southwest University
Attended From 09/01/2004 To 06/30/2006
Degree Bachelor of Business Administration Received 06/30/2006

统计、数学、经济课程：
Advanced Mathematics-2002, Probability Theory-2003, Linear Algebra-2003, Microeconomics-2004, Macroeconomics-2004, Medical Statistics-2008, Health Economic-2009
电脑编程、数据库课程：VB Programming(2004)

5187  0000      EMORY U GRAD SCH
2074  1903      CARNEGIE MELLON UNIVERSITY  PUBLIC POLICY STUDIES
1565  0000      NORTHWESTERN UNIVERSITY
5816  0616      U NORTH CAROLINA CHAPEL HILL   PUBLIC HEALTH

去北美第一要点是：选项目，既不是选博导，也不是选学校！！切记
Chengxiang Tang
MHA. Candidate
School of Public Health, Fujian Medical University
88 Jiaotong Road, Fuzhou, Fujian, 350004, PRC
Cell: 860591-13705914418
Email: tang.chengxiang@gmail.com
 
---

方向：primary care, provider, rual area, 

Health Manpower Management（Merged with Journal of Management in Medicine in 1999）

key words：
  human resources for health  最常使用
  heath human resources    这个词加拿大使用非常频繁
  health workforce
  health staff
  health manpower 原来这是90年代前用的词

  Health Personnel
  Personnel & human resources management
  Personnel management
