# Setting up Bookdown {#setup}

This tutorial will show us shortest way to build an online book (or a website)

we'll call your book "awesome-book" 

## Start on your local computer

1. Copy folder "D:\R\bookdown_template" to a reasonable place
1. Rename 2 things from "bookdown-tutorial" to "awesome-book":
  - the folder itself
  - the .Rproj file
1. Double-click the .Rproj file to launch RStudio 
1. Click on the Build tab in the top right pane to build book

## Create your "awesome-book" GitHub repo

1. Go to your GitHub account: github.com/username
1. Click on Repositories, and the green button "New" to create a new repo
1. Name this new repo "awesome-book" (DO NOT initialize this repo with a README)
1. Click the green "create repository" button
1. COPY URL

## Turn "bookdown-tutorial" into "awesome-book"

1. Go back to RStudio, to your "awesome-book" project
1. In the Console, type `usethis::use_git()` and say Yes to the two prompts. This will restart R and give you a new Git tab in the upper right pane.
1. Now, click on the Terminal tab next to the Console tab. 
1. Type `git remote add origin URL`
1. Type `git push --set-upstream origin master`

## Publish "awesome-book" (Last step) 

1. Refresh github, then files should be there! 
1. Click Settings
1. Scroll down to GitHub Pages, click "Check it out here"
1. Change the Source pulldown from "None" to "master branch /docs folder"
1. It should say "Your site is ready to be published at https://username.github.io/awesome-book/" — click the link to see!

## Moving forward

As you write your .Rmd files, build the book and commit all files, including the docs/ folder, and your published book will be updated!

